runtime: python27
api_version: 1
threadsafe: true
# [START handlers]
handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /default.css
  static_files: default.css
  upload: default.css
  mime_type: text/css

- url: /images/(.*\.(gif|png|jpg))$
  static_files: images/\1
  upload: images/.*\.(gif|png|jpg)$

- url: /search
  script: search.app
- url: /summoner
  script: summoner.app
- url: /htmltools
  static_files: htmltools.py
  upload: htmltools.py
  application_readable: true
- url: /.*
  script: main.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest

# [END libraries]