runtime: python27
api_version: 1
threadsafe: true
# [START handlers]
error_handlers:
- error_code: over_quota
  file: over_quota.html
handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css/default.css
  static_files: css/default.css
  upload: css/default.css
  mime_type: text/css
- url: /riot.txt
  static_files: riot.txt
  upload: riot.txt
- url: /images/(.*\.(gif|png|jpg))$
  static_files: images/\1
  upload: images/.*\.(gif|png|jpg)$

- url: /riotapi
  script: riotapi.app
- url: /communitydb
  script: communitydb.app
- url: /register
  script: register.app
- url: /updatecache
  script: updatecache.app
  login: admin
- url: /search
  script: search.app
- url: /summoner
  script: summoner.app
- url: /db
  script: db.app
- url: /htmltools
  static_files: htmltools.py
  upload: htmltools.py
  application_readable: true
- url: /.*
  script: main.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest

# [END libraries]